/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SpeakingRouteImport } from './routes/speaking'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as BlogRouteImport } from './routes/blog'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakingRoute = SpeakingRouteImport.update({
  id: '/speaking',
  path: '/speaking',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/blog': typeof BlogRoute
  '/experience': typeof ExperienceRoute
  '/projects': typeof ProjectsRoute
  '/speaking': typeof SpeakingRoute
  '/tools': typeof ToolsRoute
}
export interface FileRoutesByTo {
  '/blog': typeof BlogRoute
  '/experience': typeof ExperienceRoute
  '/projects': typeof ProjectsRoute
  '/speaking': typeof SpeakingRoute
  '/tools': typeof ToolsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/blog': typeof BlogRoute
  '/experience': typeof ExperienceRoute
  '/projects': typeof ProjectsRoute
  '/speaking': typeof SpeakingRoute
  '/tools': typeof ToolsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/blog' | '/experience' | '/projects' | '/speaking' | '/tools'
  fileRoutesByTo: FileRoutesByTo
  to: '/blog' | '/experience' | '/projects' | '/speaking' | '/tools'
  id:
    | '__root__'
    | '/blog'
    | '/experience'
    | '/projects'
    | '/speaking'
    | '/tools'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  BlogRoute: typeof BlogRoute
  ExperienceRoute: typeof ExperienceRoute
  ProjectsRoute: typeof ProjectsRoute
  SpeakingRoute: typeof SpeakingRoute
  ToolsRoute: typeof ToolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speaking': {
      id: '/speaking'
      path: '/speaking'
      fullPath: '/speaking'
      preLoaderRoute: typeof SpeakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  BlogRoute: BlogRoute,
  ExperienceRoute: ExperienceRoute,
  ProjectsRoute: ProjectsRoute,
  SpeakingRoute: SpeakingRoute,
  ToolsRoute: ToolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
